"""empty message

Revision ID: 13b76cad58c3
Revises: ed7cfc31558c
Create Date: 2020-08-23 19:47:07.171317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b76cad58c3'
down_revision = 'ed7cfc31558c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_type_external_id'), 'contact_type', ['external_id'], unique=True)
    op.create_table('service_offered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_offered_external_id'), 'service_offered', ['external_id'], unique=True)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('contact_date', sa.Date(), nullable=True),
    sa.Column('service_offered', sa.String(length=64), nullable=True),
    sa.Column('contact_type', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_external_id'), 'contact', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_external_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_service_offered_external_id'), table_name='service_offered')
    op.drop_table('service_offered')
    op.drop_index(op.f('ix_contact_type_external_id'), table_name='contact_type')
    op.drop_table('contact_type')
    # ### end Alembic commands ###
