"""empty message

Revision ID: 23433393e892
Revises: 4f01dc148f26
Create Date: 2020-08-24 00:44:33.619664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23433393e892'
down_revision = '4f01dc148f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    # ### end Alembic commands ###
