"""empty message

Revision ID: b732f37b51dc
Revises: 1f74e82fba0b
Create Date: 2020-08-24 19:26:59.765195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b732f37b51dc'
down_revision = '1f74e82fba0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('classroom', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'classroom')
    # ### end Alembic commands ###
