"""empty message

Revision ID: ed7cfc31558c
Revises: 1d31243c2ba0
Create Date: 2020-08-23 16:04:04.468354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7cfc31558c'
down_revision = '1d31243c2ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_type_external_id'), 'contact_type', ['external_id'], unique=True)
    op.create_table('service_offered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_offered_external_id'), 'service_offered', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_offered_external_id'), table_name='service_offered')
    op.drop_table('service_offered')
    op.drop_index(op.f('ix_contact_type_external_id'), table_name='contact_type')
    op.drop_table('contact_type')
    # ### end Alembic commands ###
