"""start and end times

Revision ID: f9250ed28a3c
Revises: 13b76cad58c3
Create Date: 2020-08-23 23:20:07.848294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9250ed28a3c'
down_revision = '13b76cad58c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('contact_end_time', sa.Time(), nullable=True))
    op.add_column('contact', sa.Column('contact_start_time', sa.Time(), nullable=True))
    op.add_column('contact', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'notes')
    op.drop_column('contact', 'contact_start_time')
    op.drop_column('contact', 'contact_end_time')
    # ### end Alembic commands ###
